name: App Weekly Release

on:
  schedule:
    - cron: '0 1 * * 0'

jobs:
  ci:
    name: App Build
    uses: ./.github/workflows/app-build.yml
    with:
      path: 'weekly'
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
